Users/profile
tubhutani13/quora-clone pull request #2
Opened 2023-01-19 16:47 UTC by tubhutani13

2023-02-01 22:37 UTC, shubhamjuneja1 commented on lib/tasks/admin.rake
> +      :verified => true,
aren't we saving verified_at instead of verified?

2023-02-01 22:43 UTC, shubhamjuneja1 commented on app/models/user.rb
> +  has_one_attached :profile_picture do |attachable|
dependent: destroy

2023-02-01 22:46 UTC, shubhamjuneja1 commented on app/models/user.rb
> +    attachable.variant :thumb, resize_to_limit: [100, 100]
extract method

2023-02-01 22:48 UTC, shubhamjuneja1 commented on app/helpers/users_helper.rb
> +    current_user.generate_change_password_token
why this is in helper????????????????

2023-02-01 22:48 UTC, shubhamjuneja1 requested changes
Changes required

2023-02-02 06:55 UTC, tubhutani13 commented on app/models/user.rb
> +    attachable.variant :thumb, resize_to_limit: [100, 100]
discuss

2023-08-03 14:45 UTC, closed without merging