added followers
tubhutani13/quora-clone pull request #8
Opened 2023-01-20 09:14 UTC by tubhutani13

2023-02-02 20:50 UTC, shubhamjuneja1 requested changes

2023-02-02 20:50 UTC, shubhamjuneja1 commented on db/migrate/20230120082902_create_follows.rb
> +      t.integer :follower_id
t.references :follower

2023-02-02 20:50 UTC, shubhamjuneja1 commented on config/routes.rb
> +  post '/users/:id/follow', to: "users#follow", as: "follow_user"
should have used  post 'follow', on: :member

2023-02-02 20:50 UTC, shubhamjuneja1 commented on config/routes.rb
> +    get '/followers', to: "users#followers"
could be simplifed
we don't need this anyways

2023-02-02 20:50 UTC, shubhamjuneja1 commented on app/views/users/_user.html.erb
> +    <%= render partial: 'questions/question', collection: @user.questions.where.not(published_at: nil) %>
@user.questions.where.not(published_at: nil) ??

2023-02-02 20:50 UTC, shubhamjuneja1 commented on app/views/users/_user.html.erb
> +      <%= button_to 'Followers', user_followers_path(@user), method: :get, class: "mt-2 btn btn-primary" %>
Please show what's the use

2023-02-02 20:50 UTC, shubhamjuneja1 commented on app/models/user.rb
> +  has_many :followees, through: :followed_users
can we use has_and_belongs_to_many

2023-02-02 20:50 UTC, shubhamjuneja1 commented on app/controllers/users_controller.rb
> +  def unfollow
we could have used single action using js
and toggle follow/unfollow

2023-02-02 20:50 UTC, shubhamjuneja1 commented on app/models/follow.rb
> +    belongs_to :follower, class_name: 'User'
do we need this modal?

2023-02-03 10:14 UTC, tubhutani13 commented on app/models/user.rb
> +  has_many :followees, through: :followed_users
please discuss

2023-08-03 14:43 UTC, merged